Use Customer_Shopping_Behaviour

Select * from customer

--Q1. What is the total revenue generated by male vs. female customers?
select gender, 
sum(purchase_amount) as total_revenue
from customer
group by gender

--Q2. Which customers used a discount but still spent more than the average purchase amount?
select customer_id, purchase_amount
from customer
where discount_applied = 'Yes' 
and purchase_amount >= (select AVG(purchase_amount) from customer)

-- Q3. Which are the top 5 products with the highest average review rating?
select top 5
item_purchased, 
round(AVG(review_rating),2) as avg_review_rating
from customer
group by item_purchased
order by AVG(review_rating) desc

--Q4. Compare the average Purchase Amounts between Standard and Express Shipping.
select shipping_type, 
AVG(purchase_amount) as avg_purchase_amount
from customer
where shipping_type in ('Standard', 'Express')
group by shipping_type

--Q5. Do subscribed customers spend more? Compare average spend and total revenue 
--between subscribers and non-subscribers.
select COUNT(customer_id) as total_customers,
subscription_status,
avg(purchase_amount) as avg_spend,
sum(purchase_amount) as total_revenue
from customer
group by subscription_status

--Q6. Which 5 products have the highest percentage of purchases with discounts applied?
Create view Purchase_percentage_wtih_discount as
select top 5 
item_purchased, 
round(100*SUM(case when discount_applied = 'Yes' then 1 else 0 end) / COUNT(*),2) as percentage_of_purchase_with_discount
from customer
group by item_purchased
order by percentage_of_purchase_with_discount desc

--Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. 
Create view Customer_Segmentation as
with customer_type as (
select customer_id, previous_purchases,
case
	when previous_purchases = 1 then 'New'
	when previous_purchases between 2 and 10 then 'Returning'
	else 'Loyal'
	end as customer_segment
from customer
)

select customer_segment, count(*) as Number_of_Customers
from customer_type
group by customer_segment

--Q8. What are the top 3 most purchased products within each category? 
Create view Categorywise_Top_products as
with item_counts as (
	select category, 
	item_purchased,
	count(customer_id) as total_orders,
	row_number() over(partition by category order by count(customer_id) desc) as item_rank
	from customer
	group by category, item_purchased
	)

select item_rank, category, item_purchased, total_orders
from item_counts
where item_rank <= 3

--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select subscription_status,
count(customer_id) as repeat_buyers
from customer
where previous_purchases > 5
group by subscription_status

--Q10. What is the revenue contribution of each age group? 
select age_group,
sum(purchase_amount) as total_revenue
from customer
group by age_group
order by total_revenue desc

--Q11 Does age group impact customer lifetime value?
Create view age_group_clv as
SELECT 
    age_group,
    COUNT(*) AS total_customers,
    SUM(estimated_clv) AS total_clv,
    AVG(estimated_clv) AS avg_clv
FROM customer
GROUP BY age_group
